# Generated by Django 4.0.6 on 2022-07-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Image', models.ImageField(null=True, upload_to='images/', verbose_name='Imagen')),
                ('Description', models.TextField(verbose_name='Descripcion')),
                ('Muscle', models.CharField(max_length=50, verbose_name='Musculo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50, verbose_name='Username')),
                ('Name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Height', models.FloatField(verbose_name='Altura')),
                ('Weight', models.FloatField(verbose_name='Peso')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, verbose_name='Nombre Rutina')),
                ('RoutineExcercise', models.ManyToManyField(to='gimnasio.excercise')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('UserNombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Weight', models.FloatField(verbose_name='Peso')),
                ('Date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('RoutineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.routine')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.user')),
            ],
        ),
    ]
