# Generated by Django 4.0.5 on 2022-07-17 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='RoutineExcercise',
        ),
        migrations.CreateModel(
            name='RoutineExcercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('ExcerciseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.excercise')),
                ('RoutineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.routine')),
            ],
        ),
    ]
